version: "3.8"

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    command: >
      sh -c "pipenv run python /code/web/manage.py makemigrations &&
             pipenv run python /code/web/manage.py migrate &&
             pipenv run python /code/web/manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./web/.env
    environment:
      - DJANGO_DEVELOPMENT=yes
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 3000:3000
      - 35729:35279
    stdin_open: true
    depends_on:
      - db

  db:
    container_name: db
    image: "postgres:13.6"
    env_file:
      - ./web/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres_data:
